"""create_clean_pdf_tables

Revision ID: 35a5b0eaf819
Revises: 
Create Date: 2025-07-23 19:42:12.459377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a5b0eaf819'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('total_pages', sa.Integer(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_metadata_filename'), 'pdf_metadata', ['filename'], unique=False)
    op.create_index(op.f('ix_pdf_metadata_id'), 'pdf_metadata', ['id'], unique=False)
    op.create_table('document_chunks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('page_number', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=False),
        sa.Column('pdf_metadata_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['pdf_metadata_id'], ['pdf_metadata.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('pdf_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pdf_id', sa.Integer(), nullable=True),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('page_number', sa.Integer(), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['pdf_id'], ['pdf_metadata.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_chunks_id'), 'pdf_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('processing_status', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_table('chunks',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('embedding_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('chunks_pkey'))
    )
    op.drop_index(op.f('ix_pdf_chunks_id'), table_name='pdf_chunks')
    op.drop_table('pdf_chunks')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_pdf_metadata_id'), table_name='pdf_metadata')
    op.drop_index(op.f('ix_pdf_metadata_filename'), table_name='pdf_metadata')
    op.drop_table('pdf_metadata')
    # ### end Alembic commands ###
