"""Describe this migration

Revision ID: e7aacf5d9f92
Revises: cf4f0b961169
Create Date: 2025-08-01 11:54:11.969338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7aacf5d9f92'
down_revision: Union[str, Sequence[str], None] = 'cf4f0b961169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feedback', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feedback', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('feedback', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feedback', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feedback', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feedback', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
